### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by pombredanne** [fprime-community/fprime-metrics-tool#2]
Hi! what would be the license for this repo? Apache-2.0 e.g. the same as fprime? I would not find one here.
Thanks!

**Comment by Joshua-Anderson** [comment]
Thanks for catching that! Yes, this project is apache 2 licensed, but we forgot to re-apply the license when breaking the metrics tools out from fprime core. Fixed in #3

**Comment by pombredanne** [comment]
Thank you ++
